@set CL=/D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE
@set LINK=/LARGEADDRESSAWARE

PATH=I:/LIB/SFML/SFML-2.2/build/lib/Release;I:/LIB/GLEW/glew-1.12.0/bin/Release/x64;%PATH%
"Projet_IN55.sln"

